default:
default:
    context:
        parameters:
            context_dir: 
              '\':           '_lib/ExmapleSite/Context'
              '\siteTwo\':  '_lib/ExampleSiteTwo/Context'
            
          
            base_url: 'http://google.com/'
            default_session: 'chrome'
            
            db_init:
              local_service:
                type: 'mysql'
                host: 'localhost'
                user: 'behat'
                password: '1'
                database: 'behat'
                port: 3306
                directory: 'local'
                init_command: 'SET NAMES "UTF8"'
              local_service_api:
                type: 'mysql'
                host: 'localhost'
                user: 'behat2'
                password: '1'
                database: 'behatTwo'
                
            sessions:
              ie8:
                host: '192.168.1.57'
                port: 9999
                
              opera:
                host: '192.168.1.57'