default:
default:
    context:
        parameters:
            base_url: 'http://google.com/'
            default_session: 'chrome'
            
            db_init:
              local_service:
                type: 'mysql'
                host: 'localhost'
                user: 'behat'
                password: '1'
                database: 'behat'
                port: 3306
                init_command: 'SET NAMES "UTF8"'
              local_service_api:
                type: 'mysql'
                host: 'localhost'
                user: 'behat2'
                password: '1'
                database: 'behatTwo'